<?php

define('MY_AFFIRMATION_PLUGIN_NAME', 'my-affirmation');
define('MY_AFFIRMATION_INCLUDE_PATH', 'inc'.DIRECTORY_SEPARATOR);
define('MY_AFFIRMATION_STYLE_NAME_ONLY', MY_AFFIRMATION_PLUGIN_NAME.'-style');
define('MY_AFFIRMATION_STYLE_NAME', MY_AFFIRMATION_STYLE_NAME_ONLY.'.css');
define('MY_AFFIRMATION_SCRIPT_NAME', MY_AFFIRMATION_PLUGIN_NAME.'.js');
define('MY_AFFIRMATION_CSS_FILENAME_FROM_INC', MY_AFFIRMATION_INCLUDE_PATH.MY_AFFIRMATION_STYLE_NAME);
define('MY_AFFIRMATION_SCRIPT_FILENAME_FROM_INC', MY_AFFIRMATION_INCLUDE_PATH.MY_AFFIRMATION_SCRIPT_NAME);
define('MY_AFFIRMATION_PLUGIN_PATH', dirname(get_theme_file_path(), 2). DIRECTORY_SEPARATOR.'plugins'.DIRECTORY_SEPARATOR.MY_AFFIRMATION_PLUGIN_NAME.DIRECTORY_SEPARATOR);
define('MY_AFFIRMATION_CSS_FILENAME_FULL_PATH', MY_AFFIRMATION_PLUGIN_PATH.MY_AFFIRMATION_INCLUDE_PATH.MY_AFFIRMATION_STYLE_NAME);
define('MY_AFFIRMATION_CSS_FILENAME_URI', plugins_url(MY_AFFIRMATION_STYLE_NAME, __FILE__));
